---
title: "Binder1"
output: html_notebook
---


#Download holepunch
```{r}
remotes::install_github("karthik/holepunch")
```
# check dependencies
```{r}
install.packages("holepunch")

```


#check rlang version needed

```{r}
pak::pkg_deps("holepunch")
```
#update rlang package
```{r}
install.packages("rlang")
```
```{r}
packageVersion("rlang")
```
#holepunch loaded next stepcomendium
```{r}
library(holepunch)
write_compendium_description(package = "B1", 
                             description = "Analysis projects")
# to write a description, with dependencies. Be sure to fill in placeholder text

write_dockerfile(maintainer = "Ashleigh_Crawford") 
# To write a Dockerfile. It will automatically pick the date of the last 
# modified file, match it to that version of R and add it here. You can 
# override this by passing r_date to some arbitrary date
# (but one for which a R version exists).

generate_badge() # This generates a badge for your readme.

# ----------------------------------------------
# At this time 🙌 push the code to GitHub 🙌
# ----------------------------------------------

# And click on the badge or use the function below to get the build 
# ready ahead of time.
build_binder()

```

#take B1 out of  build_binder

```{r}
version
```
 update to pt 1
```{r}
install.packages("installr")
library(installr)
updateR()
```
 
```{r}


```

